### ISSUE TITLE
Panic on escaped opening curly braces

### ISSUE THREAD

**Issue by ajungren** [bheisler/TinyTemplate#2]
Adding a template with an escaped opening curly brace, `\{`, causes a panic by `core::str::slice_error_fail` originating from `tinytemplate::compiler::TemplateCompiler::compile`.

Minimal test case:
```rust
use tinytemplate::TinyTemplate;

static TEMPLATE: &str = r#"hello \{world}"#;

fn main() {
    let mut tt = TinyTemplate::new();
    tt.add_template("template", TEMPLATE).expect("Unable to add template");
}
```
The panic isn't caused by `expect`, as shown in the backtrace.

Backtrace:
```
thread 'main' panicked at 'byte index 8 is out of bounds of `{world}`', src/libcore/str/mod.rs:2010:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
   9: tinytemplate::compiler::TemplateCompiler::compile
  10: tinytemplate::TinyTemplate::add_template
  11: test_case::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: main
  17: __libc_start_main
  18: _start
```

This has been tested on both `cargo 1.34.0 (6789d8a0a 2019-04-01)` and `cargo 1.36.0-nightly (759b6161a 2019-05-06)`.

**Comment by bheisler** [comment]
Hey, thanks for the bug report. I'm (pleasantly) surprised that anyone is using TinyTemplate! This should be fixed now.
